# Generated by Django 3.2.4 on 2021-07-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nombre',
        ),
    ]
