# Generated by Django 3.2.4 on 2021-07-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20210703_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='lista_productos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='Tienda.Producto'),
        ),
    ]
